items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  commentId: T:System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  id: ConfiguredTaskAwaitable`1
  parent: System.Runtime.CompilerServices
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  langs:
  - csharp
  - vb
  name: ConfiguredTaskAwaitable<TResult>
  nameWithType: ConfiguredTaskAwaitable<TResult>
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>
  type: Struct
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: ConfiguredTaskAwaitable
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 444
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: "\n<p>Provides an awaitable object that enables configured awaits on a task.</p>\n"
  remarks: "\n<p>This type is intended for compiler use; do not use it directly in your code.</p>\n"
  syntax:
    content: public struct ConfiguredTaskAwaitable<TResult>
    content.vb: Public Structure ConfiguredTaskAwaitable(Of TResult)
    typeParameters:
    - id: TResult
      description: "\n<p>The type of the result produced by this <xref href=\"System.Threading.Tasks.Task`1\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetType
  attributes:
  - type: System.Runtime.InteropServices.StructLayoutAttribute
    ctor: System.Runtime.InteropServices.StructLayoutAttribute.#ctor(System.Runtime.InteropServices.LayoutKind)
    arguments:
    - type: System.Runtime.InteropServices.LayoutKind
      value: 0
  nameWithType.vb: ConfiguredTaskAwaitable(Of TResult)
  modifiers.csharp:
  - public
  - struct
  modifiers.vb:
  - Public
  - Structure
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult)
  name.vb: ConfiguredTaskAwaitable(Of TResult)
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  commentId: M:System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  id: GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  langs:
  - csharp
  - vb
  name: GetAwaiter()
  nameWithType: ConfiguredTaskAwaitable<TResult>.GetAwaiter()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.GetAwaiter()
  type: Method
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: GetAwaiter
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 461
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: "\n<p>Returns an awaiter for this awaitable object.</p>\n"
  remarks: "\n<p>This method is intended for compiler use; do not use it directly in your code.</p>\n"
  syntax:
    content: public ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter GetAwaiter()
    content.vb: Public Function GetAwaiter As ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter
    return:
      type: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
      description: "\n<p>The awaiter.</p>\n"
  nameWithType.vb: ConfiguredTaskAwaitable(Of TResult).GetAwaiter()
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult).GetAwaiter()
references:
- uid: System.Runtime.CompilerServices
  isExternal: false
  name: System.Runtime.CompilerServices
  nameWithType: System.Runtime.CompilerServices
  fullName: System.Runtime.CompilerServices
  commentId: N:System.Runtime.CompilerServices
- uid: System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  name: Equals(Object)
  nameWithType: ValueType.Equals(Object)
  fullName: System.ValueType.Equals(System.Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  commentId: M:System.ValueType.Equals(System.Object)
- uid: System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: false
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  commentId: M:System.ValueType.GetHashCode
- uid: System.ValueType.ToString
  parent: System.ValueType
  isExternal: false
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  commentId: M:System.ValueType.ToString
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  commentId: M:System.Object.Equals(System.Object,System.Object)
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  commentId: M:System.Object.GetType
- uid: System.ValueType
  parent: System
  isExternal: false
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
  commentId: T:System.ValueType
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
  commentId: T:System.Object
- uid: System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
  commentId: N:System
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  parent: System.Runtime.CompilerServices
  isExternal: false
  name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  nameWithType: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  nameWithType.vb: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  fullname.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  name.vb: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  spec.csharp:
  - uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
    name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    nameWithType: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  - name: <
    nameWithType: <
    fullName: <
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
    name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    nameWithType: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: )
    nameWithType: )
    fullName: )
  commentId: T:System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
